import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: ".625rem",
        md: ".5rem",
        sm: ".375rem",
      },
      colors: {
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        border: "hsl(var(--border) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        ring: "hsl(var(--ring) / <alpha-value>)",
        card: {
          DEFAULT: "hsl(var(--card) / <alpha-value>)",
          foreground: "hsl(var(--card-foreground) / <alpha-value>)",
          border: "hsl(var(--card-border) / <alpha-value>)",
        },
        popover: {
          DEFAULT: "hsl(var(--popover) / <alpha-value>)",
          foreground: "hsl(var(--popover-foreground) / <alpha-value>)",
          border: "hsl(var(--popover-border) / <alpha-value>)",
        },
        primary: {
          DEFAULT: "hsl(var(--primary) / <alpha-value>)",
          foreground: "hsl(var(--primary-foreground) / <alpha-value>)",
          border: "var(--primary-border)",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary) / <alpha-value>)",
          foreground: "hsl(var(--secondary-foreground) / <alpha-value>)",
          border: "var(--secondary-border)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted) / <alpha-value>)",
          foreground: "hsl(var(--muted-foreground) / <alpha-value>)",
          border: "var(--muted-border)",
        },
        accent: {
          DEFAULT: "hsl(var(--accent) / <alpha-value>)",
          foreground: "hsl(var(--accent-foreground) / <alpha-value>)",
          border: "var(--accent-border)",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
          border: "var(--destructive-border)",
        },
        success: {
          DEFAULT: "hsl(var(--success) / <alpha-value>)",
          foreground: "hsl(var(--success-foreground) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "hsl(var(--warning) / <alpha-value>)",
          foreground: "hsl(var(--warning-foreground) / <alpha-value>)",
        },
        chart: {
          "1": "hsl(var(--chart-1) / <alpha-value>)",
          "2": "hsl(var(--chart-2) / <alpha-value>)",
          "3": "hsl(var(--chart-3) / <alpha-value>)",
          "4": "hsl(var(--chart-4) / <alpha-value>)",
          "5": "hsl(var(--chart-5) / <alpha-value>)",
        },
        sidebar: {
          ring: "hsl(var(--sidebar-ring) / <alpha-value>)",
          DEFAULT: "hsl(var(--sidebar) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-foreground) / <alpha-value>)",
          border: "hsl(var(--sidebar-border) / <alpha-value>)",
        },
        "sidebar-primary": {
          DEFAULT: "hsl(var(--sidebar-primary) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-primary-foreground) / <alpha-value>)",
          border: "var(--sidebar-primary-border)",
        },
        "sidebar-accent": {
          DEFAULT: "hsl(var(--sidebar-accent) / <alpha-value>)",
          foreground: "hsl(var(--sidebar-accent-foreground) / <alpha-value>)",
          border: "var(--sidebar-accent-border)",
        },
        blue: {
          "1": "hsl(var(--blue-1) / <alpha-value>)",
          "2": "hsl(var(--blue-2) / <alpha-value>)",
          "3": "hsl(var(--blue-3) / <alpha-value>)",
          "4": "hsl(var(--blue-4) / <alpha-value>)",
          "5": "hsl(var(--blue-5) / <alpha-value>)",
          "6": "hsl(var(--blue-6) / <alpha-value>)",
          "7": "hsl(var(--blue-7) / <alpha-value>)",
          "8": "hsl(var(--blue-8) / <alpha-value>)",
          "9": "hsl(var(--blue-9) / <alpha-value>)",
          "10": "hsl(var(--blue-10) / <alpha-value>)",
          "11": "hsl(var(--blue-11) / <alpha-value>)",
          "12": "hsl(var(--blue-12) / <alpha-value>)",
          "a1": "hsl(var(--blue-a1))",
          "a2": "hsl(var(--blue-a2))",
          "a3": "hsl(var(--blue-a3))",
          "a4": "hsl(var(--blue-a4))",
          "a5": "hsl(var(--blue-a5))",
        },
        amber: {
          "1": "hsl(var(--amber-1) / <alpha-value>)",
          "2": "hsl(var(--amber-2) / <alpha-value>)",
          "3": "hsl(var(--amber-3) / <alpha-value>)",
          "4": "hsl(var(--amber-4) / <alpha-value>)",
          "5": "hsl(var(--amber-5) / <alpha-value>)",
          "6": "hsl(var(--amber-6) / <alpha-value>)",
          "7": "hsl(var(--amber-7) / <alpha-value>)",
          "8": "hsl(var(--amber-8) / <alpha-value>)",
          "9": "hsl(var(--amber-9) / <alpha-value>)",
          "10": "hsl(var(--amber-10) / <alpha-value>)",
          "11": "hsl(var(--amber-11) / <alpha-value>)",
          "12": "hsl(var(--amber-12) / <alpha-value>)",
          "a1": "hsl(var(--amber-a1))",
          "a2": "hsl(var(--amber-a2))",
          "a3": "hsl(var(--amber-a3))",
          "a4": "hsl(var(--amber-a4))",
          "a5": "hsl(var(--amber-a5))",
        },
        gray: {
          "1": "hsl(var(--gray-1) / <alpha-value>)",
          "2": "hsl(var(--gray-2) / <alpha-value>)",
          "3": "hsl(var(--gray-3) / <alpha-value>)",
          "4": "hsl(var(--gray-4) / <alpha-value>)",
          "5": "hsl(var(--gray-5) / <alpha-value>)",
          "6": "hsl(var(--gray-6) / <alpha-value>)",
          "7": "hsl(var(--gray-7) / <alpha-value>)",
          "8": "hsl(var(--gray-8) / <alpha-value>)",
          "9": "hsl(var(--gray-9) / <alpha-value>)",
          "10": "hsl(var(--gray-10) / <alpha-value>)",
          "11": "hsl(var(--gray-11) / <alpha-value>)",
          "12": "hsl(var(--gray-12) / <alpha-value>)",
          "a1": "hsl(var(--gray-a1))",
          "a2": "hsl(var(--gray-a2))",
          "a3": "hsl(var(--gray-a3))",
          "a4": "hsl(var(--gray-a4))",
          "a5": "hsl(var(--gray-a5))",
        },
        green: {
          "1": "hsl(var(--green-1) / <alpha-value>)",
          "2": "hsl(var(--green-2) / <alpha-value>)",
          "3": "hsl(var(--green-3) / <alpha-value>)",
          "4": "hsl(var(--green-4) / <alpha-value>)",
          "5": "hsl(var(--green-5) / <alpha-value>)",
          "6": "hsl(var(--green-6) / <alpha-value>)",
          "7": "hsl(var(--green-7) / <alpha-value>)",
          "8": "hsl(var(--green-8) / <alpha-value>)",
          "9": "hsl(var(--green-9) / <alpha-value>)",
          "10": "hsl(var(--green-10) / <alpha-value>)",
          "11": "hsl(var(--green-11) / <alpha-value>)",
          "12": "hsl(var(--green-12) / <alpha-value>)",
          "a1": "hsl(var(--green-a1))",
          "a2": "hsl(var(--green-a2))",
          "a3": "hsl(var(--green-a3))",
          "a4": "hsl(var(--green-a4))",
          "a5": "hsl(var(--green-a5))",
        },
        red: {
          "1": "hsl(var(--red-1) / <alpha-value>)",
          "2": "hsl(var(--red-2) / <alpha-value>)",
          "3": "hsl(var(--red-3) / <alpha-value>)",
          "4": "hsl(var(--red-4) / <alpha-value>)",
          "5": "hsl(var(--red-5) / <alpha-value>)",
          "6": "hsl(var(--red-6) / <alpha-value>)",
          "7": "hsl(var(--red-7) / <alpha-value>)",
          "8": "hsl(var(--red-8) / <alpha-value>)",
          "9": "hsl(var(--red-9) / <alpha-value>)",
          "10": "hsl(var(--red-10) / <alpha-value>)",
          "11": "hsl(var(--red-11) / <alpha-value>)",
          "12": "hsl(var(--red-12) / <alpha-value>)",
        },
        orange: {
          "1": "hsl(var(--orange-1) / <alpha-value>)",
          "2": "hsl(var(--orange-2) / <alpha-value>)",
          "3": "hsl(var(--orange-3) / <alpha-value>)",
          "4": "hsl(var(--orange-4) / <alpha-value>)",
          "5": "hsl(var(--orange-5) / <alpha-value>)",
          "6": "hsl(var(--orange-6) / <alpha-value>)",
          "7": "hsl(var(--orange-7) / <alpha-value>)",
          "8": "hsl(var(--orange-8) / <alpha-value>)",
          "9": "hsl(var(--orange-9) / <alpha-value>)",
          "10": "hsl(var(--orange-10) / <alpha-value>)",
          "11": "hsl(var(--orange-11) / <alpha-value>)",
          "12": "hsl(var(--orange-12) / <alpha-value>)",
          "a1": "hsl(var(--orange-a1))",
          "a2": "hsl(var(--orange-a2))",
          "a3": "hsl(var(--orange-a3))",
          "a4": "hsl(var(--orange-a4))",
          "a5": "hsl(var(--orange-a5))",
        },
        pink: {
          "1": "hsl(var(--pink-1) / <alpha-value>)",
          "2": "hsl(var(--pink-2) / <alpha-value>)",
          "3": "hsl(var(--pink-3) / <alpha-value>)",
          "4": "hsl(var(--pink-4) / <alpha-value>)",
          "5": "hsl(var(--pink-5) / <alpha-value>)",
          "6": "hsl(var(--pink-6) / <alpha-value>)",
          "7": "hsl(var(--pink-7) / <alpha-value>)",
          "8": "hsl(var(--pink-8) / <alpha-value>)",
          "9": "hsl(var(--pink-9) / <alpha-value>)",
          "10": "hsl(var(--pink-10) / <alpha-value>)",
          "11": "hsl(var(--pink-11) / <alpha-value>)",
          "12": "hsl(var(--pink-12) / <alpha-value>)",
          "a1": "hsl(var(--pink-a1))",
          "a2": "hsl(var(--pink-a2))",
          "a3": "hsl(var(--pink-a3))",
          "a4": "hsl(var(--pink-a4))",
          "a5": "hsl(var(--pink-a5))",
        },
        cyan: {
          "1": "hsl(var(--cyan-1) / <alpha-value>)",
          "2": "hsl(var(--cyan-2) / <alpha-value>)",
          "3": "hsl(var(--cyan-3) / <alpha-value>)",
          "4": "hsl(var(--cyan-4) / <alpha-value>)",
          "5": "hsl(var(--cyan-5) / <alpha-value>)",
          "6": "hsl(var(--cyan-6) / <alpha-value>)",
          "7": "hsl(var(--cyan-7) / <alpha-value>)",
          "8": "hsl(var(--cyan-8) / <alpha-value>)",
          "9": "hsl(var(--cyan-9) / <alpha-value>)",
          "10": "hsl(var(--cyan-10) / <alpha-value>)",
          "11": "hsl(var(--cyan-11) / <alpha-value>)",
          "12": "hsl(var(--cyan-12) / <alpha-value>)",
          "a1": "hsl(var(--cyan-a1))",
          "a2": "hsl(var(--cyan-a2))",
          "a3": "hsl(var(--cyan-a3))",
          "a4": "hsl(var(--cyan-a4))",
          "a5": "hsl(var(--cyan-a5))",
        },
        teal: {
          "1": "hsl(var(--teal-1) / <alpha-value>)",
          "2": "hsl(var(--teal-2) / <alpha-value>)",
          "3": "hsl(var(--teal-3) / <alpha-value>)",
          "4": "hsl(var(--teal-4) / <alpha-value>)",
          "5": "hsl(var(--teal-5) / <alpha-value>)",
          "6": "hsl(var(--teal-6) / <alpha-value>)",
          "7": "hsl(var(--teal-7) / <alpha-value>)",
          "8": "hsl(var(--teal-8) / <alpha-value>)",
          "9": "hsl(var(--teal-9) / <alpha-value>)",
          "10": "hsl(var(--teal-10) / <alpha-value>)",
          "11": "hsl(var(--teal-11) / <alpha-value>)",
          "12": "hsl(var(--teal-12) / <alpha-value>)",
          "a1": "hsl(var(--teal-a1))",
          "a2": "hsl(var(--teal-a2))",
          "a3": "hsl(var(--teal-a3))",
          "a4": "hsl(var(--teal-a4))",
          "a5": "hsl(var(--teal-a5))",
        },
        violet: {
          "1": "hsl(var(--violet-1) / <alpha-value>)",
          "2": "hsl(var(--violet-2) / <alpha-value>)",
          "3": "hsl(var(--violet-3) / <alpha-value>)",
          "4": "hsl(var(--violet-4) / <alpha-value>)",
          "5": "hsl(var(--violet-5) / <alpha-value>)",
          "6": "hsl(var(--violet-6) / <alpha-value>)",
          "7": "hsl(var(--violet-7) / <alpha-value>)",
          "8": "hsl(var(--violet-8) / <alpha-value>)",
          "9": "hsl(var(--violet-9) / <alpha-value>)",
          "10": "hsl(var(--violet-10) / <alpha-value>)",
          "11": "hsl(var(--violet-11) / <alpha-value>)",
          "12": "hsl(var(--violet-12) / <alpha-value>)",
          "a1": "hsl(var(--violet-a1))",
          "a2": "hsl(var(--violet-a2))",
          "a3": "hsl(var(--violet-a3))",
          "a4": "hsl(var(--violet-a4))",
          "a5": "hsl(var(--violet-a5))",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        serif: ["Georgia", "serif"],
        mono: ["JetBrains Mono", "monospace"],
        display: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "0": ["10px", { lineHeight: "14px" }],
        "1": ["12px", { lineHeight: "16px" }],
        "2": ["14px", { lineHeight: "20px" }],
        "3": ["16px", { lineHeight: "24px" }],
        "4": ["18px", { lineHeight: "26px" }],
        "5": ["20px", { lineHeight: "28px" }],
        "6": ["24px", { lineHeight: "30px" }],
        "7": ["28px", { lineHeight: "36px" }],
        "8": ["32px", { lineHeight: "40px" }],
        "9": ["40px", { lineHeight: "48px" }],
      },
      backdropBlur: {
        frosted: "20px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(10px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out forwards",
        "fade-up": "fade-up 0.4s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        shimmer: "shimmer 2s linear infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
